reuters-graphics/graphics-components

package.json
src/components/Framer/Framer.svelte
src/components/Framer/Typeahead/fuzzy.js
src/components/Framer/Typeahead/index.svelte
yarn.lock

closes #25

---

src/components/SEO/SEO.svelte
src/components/SEO/stories/docs/component.md
src/components/SEO/stories/docs/quickit.md

closes #38

---

src/components/ReferralBlock/ReferralBlock.stories.svelte
src/components/ReferralBlock/ReferralBlock.svelte
src/components/ReferralBlock/stores.js
src/components/ReferralBlock/stories/docs/component.md
src/components/SiteHeader/MobileMenu/index.svelte
src/index.js

Referrals block

---

package.json
src/components/PhotoCarousel/PhotoCarousel.stories.svelte
src/components/PhotoCarousel/PhotoCarousel.svelte
src/components/PhotoCarousel/stories/docs/component.md
src/components/PhotoCarousel/stories/docs/withCustom.md
src/components/PhotoCarousel/stories/photos.json
src/index.js
yarn.lock

basic carousel

---

src/components/@types/global.ts
src/components/Scroller/Embedded/Background.svelte
src/components/Scroller/Embedded/Foreground.svelte
src/components/Scroller/Foreground.svelte
src/components/Scroller/Scroller.stories.svelte
src/components/Scroller/Scroller.svelte
src/components/Scroller/docProps.ts
src/components/Scroller/stories/docs/ai2svelte.md
src/components/Scroller/stories/docs/component.md
src/components/Scroller/stories/docs/interactive.md
src/components/Scroller/stories/docs/quickit.md
src/components/Video/docs.svx

Hides all background graphics, adds alt text option for each step, and updates docs. See this for more detail https://github.com/reuters-graphics/graphics-components/issues/13
Details of what's changed:
- Background divs now have `aria-hidden=true` in the interactive and embed components
- Updates `docProps` to pull AltText from google doc
- Visibly hidden alt text, if it exists, is added after the foreground text in the interactive and embed components
- Updates docs to include the altText prop. Explains that you can either add alt text to each step or to just the first step if you want to describe all graphics in the scroll section in one alt text.

Accessibility updates to Scroller

---

src/components/DocumentCloud/DocumentCloud.stories.svelte
src/components/DocumentCloud/DocumentCloud.svelte
src/components/DocumentCloud/stories/docs/component.md
src/index.js

Adds a new component for embedding DocumentCloud document.

Add DocumentCloud component

---

.github/workflows/release.yaml

release workflow

---

src/components/SEO/SEO.svelte

Fixes canonical URL issue #82.

closes #82

---

src/components/Scroller/docProps.ts

allow preload in Google block for scroller. closes #81

---

src/components/EndNotes/docProps.ts
src/components/EndNotes/stories/docs/component.md
src/components/HeroHeadline/Hero.stories.svelte

Docs fixes and chromatic ignore header in hero headline

---

src/components/ReferralBlock/ReferralBlock.stories.svelte
src/components/ReferralBlock/ReferralBlock.svelte
src/components/ReferralBlock/stores.js
src/components/ReferralBlock/stories/docs/collection.md
src/components/ReferralBlock/stories/docs/component.md

Fixes ReferralBlock for sections and adds handling for Arc collections.

Referral block fix

---

src/components/SiteFooter/Referrals/Link.svelte

Tell us what this PR does or link to any related issues that describe the goal here.

closes #132

---

src/components/Scroller/Background.svelte

Tell us what this PR does or link to any related issues that describe the goal here.

Fix scroller bug not updating on Safari

---

src/components/AdSlot/SponsorshipAd.stories.svelte
src/components/AdSlot/SponsorshipAd.svelte
src/components/AdSlot/stories/docs/inline.md
src/components/AdSlot/stories/docs/sponsorship.md
src/index.js

Sponsorship ad

---

src/components/AdSlot/LeaderboardAd.stories.svelte
src/components/AdSlot/LeaderboardAd.svelte
src/components/AdSlot/SponsorshipAd.svelte
src/components/AdSlot/stories/docs/leaderboard.md
src/index.js

First draft at static leaderboard.

Leaderboard ad

---

src/components/Analytics/providers/ga.ts

Update to TR's GA account

---

src/components/AdSlot/SponsorshipAd.svelte

fixed height for sponsorship ad

---

src/components/AdSlot/LeaderboardAd.stories.svelte
src/components/AdSlot/LeaderboardAd.svelte

sticky leaderboard

---

src/components/SiteFooter/SiteFooter.stories.svelte
src/components/SiteFooter/SiteFooter.svelte
src/components/SiteFooter/stories/docs/removeReferrals.md

can remove graphics referrals from footer

---

src/components/AdSlot/SponsorshipAd.svelte

sponsorship ad dimensions

---

src/components/AdSlot/AdSlot.svelte

Use placement name as div_id targeting value

---

src/components/AdSlot/@types/ads.ts
src/components/AdSlot/AdSlot.svelte
src/components/AdSlot/InlineAd.svelte
src/components/AdSlot/LeaderboardAd.svelte
src/components/AdSlot/ResponsiveAd.svelte
src/components/AdSlot/SponsorshipAd.svelte
src/components/AdSlot/stories/docs/inline.md

Updates ad types and placement names.

Ad types and placement names

---

.changeset/pink-penguins-brush.md
src/components/SiteHeader/NavBar/NavDropdown/StoryCard/index.svelte
src/components/SiteHeader/NavBar/NavDropdown/index.svelte

Fix more menu

---

.changeset/clever-timers-wonder.md
src/components/Analytics/Analytics.svelte
src/components/Analytics/providers/index.ts
src/components/Analytics/providers/parsely.ts
src/components/SEO/SEO.svelte
src/globals.d.ts

Adds parsely tracking, based on [RCOM's implementation](https://github.com/tr/rcom-arc_fusion/blob/34199f578fd13b1cb2d57dc012a0e54d39adb8f9/src/websites/common/parse-ly/index.js#L4)

Parsely tracking

---

.changeset/khaki-experts-bow.md
.storybook/add-ons/canvas-docs/Tab.tsx
.storybook/add-ons/canvas-docs/constants.ts
.storybook/add-ons/canvas-docs/index.tsx
.storybook/manager.ts
package.json
pnpm-lock.yaml
src/components/Block/Block.stories.svelte
src/components/ReferralBlock/ReferralBlock.svelte
src/components/SiteHeader/NavBar/NavDropdown/StoryCard/index.svelte

Fixes header nav to account for changes in thumbnail API, with fallback to previous schema in case https://github.com/tr/rcom-arc_raptor-ui/issues/6541 gets traction..

Header fix

---

src/components/Byline/Byline.mdx
src/components/Byline/Byline.svelte

Quick PR to add ArchieML example

Adds ArchieML example to docs

---

src/components/DocumentCloud/DocumentCloud.mdx
src/components/DocumentCloud/DocumentCloud.stories.svelte
src/components/DocumentCloud/DocumentCloud.svelte

- Migrates to Svelte 5
Nothing much here; just simple migration.

Updates DocumentCloud

---

src/components/SimpleTimeline/SimpleTimeline.mdx
src/components/SiteHeadline/SiteHeadline.mdx

Fixes typos and some inconsistencies in ArchieML documentation.

Docs fixes

---

.changeset/rude-beers-drive.md
src/components/SiteFooter/CompanyLinks.svelte
src/components/SiteHeader/MobileMenu/index.svelte
src/components/SiteHeader/NavBar/NavDropdown/index.svelte
src/components/SiteHeader/NavBar/index.svelte

Fixes a11y issues in the SiteHeader and SiteFooter component

Header footer a11y

---

.changeset/easy-dryers-chew.md
src/components/Framer/Dropdown/index.svelte
src/components/Framer/Framer.svelte

Adds a searchType prop to Framer and defaults to a simple dropdown.

Framer searchType

---

src/components/Headpile/Headpile.svelte
src/components/Headpile/Headshot.svelte
src/components/Headpile/KeyFigure.svelte

Adds layout edits as per https://github.com/reuters-graphics/graphics-components/pull/307#issuecomment-2904028780

edits headpile

---

src/components/ScrollerBase/ScrollerBase.svelte
src/components/ScrollerBase/demo/ScrollerDemo.svelte

Makes `width` prop reactive as per #317

Reactive `width` for ScrollerBase

---

.changeset/warm-rocks-travel.md
src/components/AdSlot/adScripts/bootstrap.ts

Tell us what this PR does or link to any related issues that describe the goal here.

Updated oneTrustId from a test one to the actual production one

---

src/components/ScrollerVideo/ScrollerVideo.mdx
src/components/ScrollerVideo/demo/Embedded.svelte

- Replaces dummy grey boxes in Embed demo with dummy body text. I found the grey boxes confusing
- Small tweaks

Quickfixes to the embed demo

---

src/components/ScrollerVideo/ScrollerVideo.mdx

fixes docs
